# Dashboards need to be specified here to be created on TestGrid
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: googleoss-gcp-guest
- name: googleoss-test-infra
- name: googleoss-esp-v2-presubmit
- name: googleoss-esp-v2-periodic
- name: googleoss-en-server
- name: googleoss-kubeflow-pipelines
- name: googleoss-kubeflow-gcp-blueprints

dashboard_groups:
  - name: googleoss
    dashboard_names:
    - googleoss-gcp-guest
    - googleoss-test-infra
    - googleoss-esp-v2-presubmit
    - googleoss-esp-v2-periodic
    - googleoss-en-server
  - name: googleoss-kubeflow
    dashboard_names:
    - googleoss-kubeflow-pipelines
    - googleoss-kubeflow-gcp-blueprints
